### ISSUE TITLE
Production and Tests use the same db

### ISSUE THREAD

**Issue by aspedrosa** [aspedrosa/CloudIT#12]
Some tests, if not all, are using the same database that is used for production.
We can resolve this by:
- On mysql have two databases (db and tests) so there's a clear separation between them;
- Launch a mysql container before tests

However both approaches can have problems since we are using a multibranch pipeline. If the tests of different branches run concurrently multiple tests applications will use the same database. For the second approach the problem will occur if multiple containers are launched using the same port.

We discussed in using h2 for tests but I found [this](https://phauer.com/2017/dont-use-in-memory-databases-tests-h2/), but the problem mentioned there might not be a problem for us

**Comment by joao-alegria** [comment]
To which solution are you more inclined to use? H2?

**Comment by aspedrosa** [comment]
Were you able to make it use h2 during tests?

**Comment by joao-alegria** [comment]
No, that's why I asked. For some reason when running tests locally the security component seems to struggle fetching the information from the database.
And I also struggled to run the tests locally when using the phantomjs driver.
