### ISSUE TITLE
Use the same window for selenium tests

### ISSUE THREAD

**Issue by aspedrosa** [aspedrosa/CloudIT#20]
For each feature cucumber instantiates the class StepDefs which leads to the initialization of multiple geckodrivers leading to a high usage of memory.

A work around for this is to initialize the driver on the static block of the class StepDefs.

Furthermore, on all features cucumber tests we call the method quit() but we could remove this, what can bring a speed up on tests.

**Comment by adebna** [comment]
To do that it's necessary for the WebDriver to be a static variable.
But I don't think that will be a problem.

It will be needed some refactor on some tests, and there is the problem that if some test fails the browser will "block" and I don't no how it will react if we try to do an operation on it.

**Comment by aspedrosa** [comment]
Fixed with merge of #19
