### ISSUE TITLE
Test coverage not working

### ISSUE THREAD

**Issue by aspedrosa** [aspedrosa/CloudIT#7]
Both sonarqube and cobertube plugin on jenking are not getting any test coverage

**Comment by adebna** [comment]
Já exprimentas-te colocar o plugin do jacoco no pom.xml ?

**Comment by aspedrosa** [comment]
Não, só vi isso do jacoco depois dos meus commits.
Para além disso estou a fazer exclude do juni4 e a por o 5.

**Comment by aspedrosa** [comment]
Fixed with 99d3fb6b293da98641a84bcd7d577c72d7ad6530
